### ISSUE TITLE
dada2 parallelization support

### ISSUE THREAD

**Issue by m-murphy** [EPPIcenter/mad4hatter#114]
We should split up the dada_overlaps script into 3 scripts

1. fit error model
2. infer variants (call `dada()`) for each sample <- this can be parallelized across all samples
3. merge results

this will be super helpful for running on AWS

**Comment by m-murphy** [comment]
https://benjjneb.github.io/dada2/bigdata.html like this

**Comment by bgpalmer** [comment]
pr #115
