### ISSUE TITLE
masked tandem repeats

### ISSUE THREAD

**Issue by aarandad** [EPPIcenter/mad4hatter#41]
make trf step part of the pipeline
run if files haven't been generated
leave as option to mask them

**Comment by palmbri** [comment]
@aarandad - tandem repeats + option to mask are straightforward, but the conditional logic to operate depending on the presence of a masked file has been challenging. After some exhaustive searching, it looks like it's easier to do in DSL2 which is logged in #36

**Comment by palmbri** [comment]
per: https://groups.google.com/g/nextflow/c/L8SLjVWVyqc
