### ISSUE TITLE
add to sample_coverage file the # of reads that map to Pf

### ISSUE THREAD

**Issue by jbriggs7** [EPPIcenter/mad4hatter#69]
Currently I think the "Amplicons" output in the sample_coverage file is just telling you which reads have the correct primer sequences. However, that doesn't mean they actually map to Pf -- which is what is most useful to know. You can get this data out of the allele data file, but it would be nice to have it summarized in the sample_coverage file. Discussed w/Andres & he agrees

**Comment by bgpalmer** [comment]
merged
