### ISSUE TITLE
fixing graphs in the QC htmls that are created 

### ISSUE THREAD

**Issue by jbriggs7** [EPPIcenter/mad4hatter#72]
Hi, 

If you do a big run with multiple samples, the QC graphs are all smushed and very small. Andres said there was a fix for this that got lost in a merge at some point. Anyway hoping we can get it re-fixed, since the code is probably out there in the world somewhere. 

Thanks!

**Comment by manuelgug** [comment]
@jbriggs7 this issue has been fixed in #73 . Now you get individual pdfs that fit >200 graphs each.
